package com.yatenesturno.activities.job_edit.service_configs;

public enum ConfigurationId {
    PRICE,
    CONCURRENCY,
    EMERGENCY, DAY_PICKER, CREDITS, DAYS_AND_DURATION, REMINDER,
    CONCURRENT_SERVICES, FIXED_SCHEDULE, CLASS, INTERVAL, TIME_SLOT,CREDIT_SYSTEM,SIMULT_SHIFTS,CLIENT_PERMISSIONS,BASIC_SERVICE_CONFIG
}

